name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --omit=dev
    
    - name: Create deployment package
      run: |
        tar -czf deployment.tar.gz \
          --exclude=node_modules \
          --exclude=.git \
          --exclude=tests \
          --exclude=.github \
          --exclude=coverage \
          --exclude=docs \
          .
    
    - name: Deploy
      run: |
        echo "Deploying to ${{ github.event.inputs.environment }}..."
        echo "Deployment package created: deployment.tar.gz"
    
    - name: Deployment complete
      run: echo "Deployment to ${{ github.event.inputs.environment }} completed!"